# Generated by Django 5.1.3 on 2024-11-19 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aboutus',
            table='about_us_models',
        ),
        migrations.AlterModelTable(
            name='bannermodel',
            table='banner',
        ),
    ]
