# Generated by Django 5.1.3 on 2024-11-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='due_amount',
            field=models.FloatField(blank=True, default=500, null=True),
        ),
    ]
