# Generated by Django 5.1.3 on 2024-11-16 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_payment_due_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='mission_statement',
            new_name='mission',
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='vision_statement',
            new_name='vision',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='history',
        ),
    ]
