# Generated by Django 5.1.3 on 2024-11-17 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientprogressdetails',
            old_name='overview',
            new_name='progress',
        ),
    ]
