# Generated by Django 5.1.3 on 2024-11-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_overview_clientprogressdetails_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'pending'), ('CONFIRMED', 'confirmed'), ('DONE', 'done'), ('CANCELLED', 'cancelled'), ('REJECTED', 'rejected')], default='PENDING', max_length=100, null=True),
        ),
    ]
