# Generated by Django 5.1.3 on 2024-11-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_achievements_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='thumbnail',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='videojournal',
            old_name='thumbnail',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='videojournal',
            old_name='journal_link',
            new_name='video_link',
        ),
        migrations.RemoveField(
            model_name='appointmentrequest',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='review',
            name='client_name',
        ),
        migrations.AlterField(
            model_name='achievements',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'pending'), ('APPROVED', 'approved'), ('REJECTED', 'rejected')], default='PENDING', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'pending'), ('APPROVED', 'approved'), ('REJECTED', 'rejected')], default='PENDING', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='faqmodel',
            name='is_published',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_published',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'pending'), ('APPROVED', 'approved'), ('REJECTED', 'rejected')], default='PENDING', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='videojournal',
            name='is_published',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='videojournal',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'pending'), ('APPROVED', 'approved'), ('REJECTED', 'rejected')], default='PENDING', max_length=100, null=True),
        ),
    ]
