# Generated by Django 5.1.3 on 2024-11-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usermodel_gender_usermodel_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
