# Generated by Django 5.1.3 on 2024-11-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_clientprofilemodel_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselorprofilemodel',
            name='pay_per_session',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientprofilemodel',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'pending'), ('CONFIRMED', 'confirmed'), ('DONE', 'done'), ('CANCELLED', 'cancelled'), ('REJECTED', 'rejected')], default='PENDING', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='counselorprofilemodel',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'pending'), ('CONFIRMED', 'confirmed'), ('DONE', 'done'), ('CANCELLED', 'cancelled'), ('REJECTED', 'rejected')], default='PENDING', max_length=100, null=True),
        ),
    ]
