# Generated by Django 5.1.3 on 2024-11-19 14:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_counselorprofilemodel_pay_per_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofilemodel',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'pending'), ('APPROVED', 'approved'), ('REJECTED', 'rejected')], default='PENDING', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='counselorprofilemodel',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'pending'), ('APPROVED', 'approved'), ('REJECTED', 'rejected')], default='PENDING', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text="Unique id for a model's object", primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Is the model's object active")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text="Creation date of the model's object")),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text="Updating date of the model's object")),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('awarded_by', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'pending'), ('APPROVED', 'approved'), ('REJECTED', 'rejected')], default='PENDING', max_length=100, null=True)),
                ('counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counselor_achievements', to='user_profile.counselorprofilemodel')),
            ],
            options={
                'db_table': 'achievements',
                'ordering': ['-created_at'],
            },
        ),
    ]
