# Generated by Django 5.1.3 on 2024-11-19 14:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule_management', '0001_initial'),
        ('user_profile', '0004_alter_clientprofilemodel_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text="Unique id for a model's object", primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Is the model's object active")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text="Creation date of the model's object")),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text="Updating date of the model's object")),
                ('booking_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'pending'), ('ASSIGNED', 'assigned'), ('COMPLETED', 'completed'), ('CANCELLED', 'cancelled'), ('REJECTED', 'rejected')], default='PENDING', max_length=100, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_request', to='user_profile.clientprofilemodel')),
                ('counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counselor_request', to='user_profile.counselorprofilemodel')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_schedule', to='schedule_management.counselorschedule')),
            ],
            options={
                'db_table': 'appointment_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
